language: java

sudo: false

matrix:
  include:
    # Headed Linux
    - os: linux
      dist: trusty
      jdk: oraclejdk8
    
addons:
  apt:
    packages:
      - oracle-java8-installer

before_install:
  - if [[ "${TRAVIS_OS_NAME}" == linux ]]; then export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start; fi

install: ./gradlew clean check

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - ./gradlew sonar
